### ISSUE TITLE
Controller method is always called - even if cached response exists and sent back.

### ISSUE THREAD

**Issue by duginov** [Jaxelr/Nancy.RapidCache#66]
# Describe the question

I discovered that regardless of existing cache entry controller's method is always called in a separate thread. Tracing shows that module is created twice on different threads (two constructor calls), one thread finds cached response in the store and return it to caller. However on a different thread "regular" call is executed - potentially accessing expensive resource which looks like waste. **Is that by design or it's a bug?** One would probably expect no attempt to execute controller's code if cached response is available.

## Steps to reproduce (if applicable)

In Nancy.RapidCache.SampleApplication.Net452, put tracepoints on module's constructor and the actual code responding to the call. After first call (which creates cached response), on every request controller method executes. Screenshot: https://i.imgur.com/iSYY91h.png

- Dotnet version: [netcore2, dotnet452]
- Library version: [0.3.0]

**Comment by Jaxelr** [comment]
Hi, thanks for opening the issue, ill take a peek in the next few days since ive been sort of swamp. 👎

Edit: To be clear, no, it shouldnt be called if is on the CacheStore created and Non-Expired.

**Comment by Jaxelr** [comment]
Found the bug, I will be doing some regression testing from my part and hopefully will be posting soon a newer version of the lib via nuget.

**Comment by Jaxelr** [comment]
Just released 0.3.2 on nuget which should address this issue.
