### ISSUE TITLE
No support for .NET Framework 4.5.2 in 0.4.0?

### ISSUE THREAD

**Issue by duginov** [Jaxelr/Nancy.RapidCache#75]
I just found that nuget package for 0.4.0 has only .NETStandard 2.0 support. Is this intentional or just an oversight? We're still using it with framework 4.5.2...

- Dotnet version: N/A
- Library version: [0.4.0]

**Comment by Jaxelr** [comment]
One of the features i added includes dependencies that are over net452, but i think i can make it work on 452, Ill keep this issue open while i work on it for a few days

**Comment by Jaxelr** [comment]
Just uploaded to myget 0.4.1 that includes support for net452, i will do some tests in the next days and release it on nuget, will close this issue once that happens

**Comment by Jaxelr** [comment]
Published to nuget version 0.4.1 that adds back net452 support.

**Comment by duginov** [comment]
Not sure whether it's related to latest update, but it looks like 0.4.1 nuget lib lists not-exactly-correct dependency on "StackExchange.Redis > 1.2.6"
It looks like it also needs to be <2.0.0 because if I try to update to  2.0.601, I'm getting this error on the line where RedisCacheStore constructor called:

`The type 'ConfigurationOptions' is defined in an assembly that is not referenced. You must add a reference to assembly 'StackExchange.Redis, Version=1.2.6.0, Culture=neutral, PublicKeyToken=null'.	
`

Just FYI, this is not a big issue since 1.2.6 works fine

**Comment by Jaxelr** [comment]
Thanks for pointing this out, I will take a look 👍

**Comment by Jaxelr** [comment]
StachExchange.Redis 2.+ raises the minimal dependency to .net framework 4.6.

![image](https://user-images.githubusercontent.com/5913008/58847426-f22c3580-8650-11e9-85e0-7941a46f6366.png)

So in order to use net 4.5.X the version 1.X is used.

![image](https://user-images.githubusercontent.com/5913008/58847513-39b2c180-8651-11e9-92a7-bffba3a88b8e.png)
